version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: boilerplate-mariadb
    environment:
      MYSQL_DATABASE: commerce
      MYSQL_USER: commerce_user
      MYSQL_PASSWORD: commerce_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - boilerplate-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: boilerplate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boilerplate-network

  # Kafka with Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: boilerplate-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - boilerplate-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: boilerplate-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - boilerplate-network

  # Eureka Service Discovery
  eureka:
    image: springcloud/eureka
    container_name: boilerplate-eureka
    ports:
      - "8761:8761"
    networks:
      - boilerplate-network

volumes:
  mariadb_data:
  redis_data:

networks:
  boilerplate-network:
    driver: bridge