name: Test Coverage Report

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      checks: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests with JaCoCo
      run: ./gradlew clean testAll jacocoRootReport --no-daemon --no-build-cache --info
    
    - name: Debug - Check JaCoCo report generation
      run: |
        echo "=== Checking build directory structure ==="
        if [ -d build/reports/jacoco ]; then
          echo "JaCoCo reports directory exists"
          find build/reports/jacoco -type f -name "*.csv" -o -name "*.xml" | head -20
        else
          echo "JaCoCo reports directory does not exist"
        fi
        echo "=== Checking Maven-compatible directory structure ==="
        if [ -d target/site/jacoco ]; then
          echo "Maven-compatible directory exists"
          ls -la target/site/jacoco/
        else
          echo "Maven-compatible directory does not exist"
        fi
    
    - name: Ensure JaCoCo reports exist
      run: |
        echo "=== Ensuring JaCoCo reports exist in Maven-compatible directory ==="
        # Wait a moment for file system sync
        sleep 2
        
        # Check if reports were generated
        if [ ! -f target/site/jacoco/jacoco.csv ]; then
          echo "ERROR: JaCoCo CSV report not found at target/site/jacoco/jacoco.csv"
          echo "Attempting to manually copy from build directory..."
          
          # Try to manually copy if not present
          if [ -f build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv ]; then
            mkdir -p target/site/jacoco
            cp build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv target/site/jacoco/jacoco.csv
            cp build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml target/site/jacoco/jacoco.xml
            echo "Manually copied reports to Maven-compatible directory"
          else
            echo "ERROR: No JaCoCo reports found in build directory either"
            find . -name "*.csv" -path "*/jacoco/*" 2>/dev/null || echo "No CSV files found"
            exit 1
          fi
        fi
        
        # Verify final state
        if [ -f target/site/jacoco/jacoco.csv ] && [ -f target/site/jacoco/jacoco.xml ]; then
          echo "SUCCESS: JaCoCo reports are available"
          echo "Contents of target/site/jacoco:"
          ls -la target/site/jacoco/
        else
          echo "ERROR: Failed to ensure JaCoCo reports exist"
          exit 1
        fi
    
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        generate-summary: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv
    
    - name: Log coverage percentages
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branches = ${{ steps.jacoco.outputs.branches }}"
    
    - name: JaCoCo Report
      id: jacoco-report
      uses: madrapps/jacoco-report@v1.6.1
      continue-on-error: true
      with:
        paths: |
          ${{ github.workspace }}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 70
        min-coverage-changed-files: 70
        title: 'JaCoCo Test Coverage Report'
        update-comment: true
        skip-if-no-changes: true
        pass-emoji: '✅'
        fail-emoji: '❌'
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports
        path: |
          build/reports/jacoco/jacocoRootReport/html/
          **/build/reports/jacoco/test/html/
        retention-days: 7
    
    - name: Check coverage threshold
      run: ./gradlew jacocoTestCoverageVerification
      continue-on-error: true
    
    - name: Comment PR with coverage
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const coverage = '${{ steps.jacoco.outputs.coverage }}';
          const branches = '${{ steps.jacoco.outputs.branches }}';
          
          const comment = `## Test Coverage Report 📊
          
          | Metric | Coverage |
          |--------|----------|
          | Lines | ${coverage}% |
          | Branches | ${branches}% |
          
          ✅ Minimum coverage threshold: 70%
          
          View detailed report in the [Actions artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });